export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_FULLFILLED = 'FETCH_USERS_FULLFILLED';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';

export const FETCH_CHATS_PENDING = 'FETCH_CHATS_PENDING';
export const FETCH_CHATS_FULLFILLED = 'FETCH_CHATS_FULLFILLED';
export const FETCH_CHATS_REJECTED = 'FETCH_CHATS_REJECTED';
export const SELECT_CHAT = 'SELECT_CHAT';

export const FETCH_MESSAGES_PENDING = 'FETCH_MESSAGES_PENDING';
export const FETCH_MESSAGES_FULLFILLED = 'FETCH_MESSAGES_FULLFILLED';
export const FETCH_MESSAGES_REJECTED = 'FETCH_MESSAGES_REJECTED';

export const CREATE_MESSAGES_PENDING = 'CREATE_MESSAGES_PENDING';
export const CREATE_MESSAGES_FULLFILLED = 'CREATE_MESSAGES_FULLFILLED';
export const CREATE_MESSAGES_REJECTED = 'CREATE_MESSAGES_REJECTED';